INFO  2022-11-18 17:21:44,112 minitest.py _miniSetUp      279 =========Current case: test_02_page_base_element=========
INFO  2022-11-18 17:21:44,112 minitest.py _miniSetUp      280 package info: D:.E护通.自动化.miniapp_auto.case.homepage_test, case info: HomePageTest.test_02_page_base_element
INFO  2022-11-18 17:21:44,112 basenative.py wrapper         23  call BaseNative.back_to_miniprogram
INFO  2022-11-18 17:21:44,112 basenative.py back_to_miniprogram 528 try back_to_miniprogram 3
INFO  2022-11-18 17:21:44,113 basenative.py wrapper         27  call BaseNative.back_to_miniprogram end
INFO  2022-11-18 17:21:44,113 app.py     relaunch        387 ReLaunch: /pages/user/userindex
DEBUG 2022-11-18 17:21:44,113 connection.py send_async      211 ASYNC_SEND > {"id": "9a0ed220-b29f-49ad-9a02-84dfdda8d3b5", "method": "App.callWxMethod", "params": {"method": "reLaunch", "args": [{"url": "/pages/user/userindex"}]}}
DEBUG 2022-11-18 17:21:44,186 connection.py _on_message     252 RECV < {"id":"9a0ed220-b29f-49ad-9a02-84dfdda8d3b5","result":{"result":{"errMsg":"reLaunch:ok"}}}
INFO  2022-11-18 17:21:44,187 connection.py _on_message     273 received async msg: 9a0ed220-b29f-49ad-9a02-84dfdda8d3b5
DEBUG 2022-11-18 17:21:44,579 connection.py _on_message     252 RECV < {"method":"App.bindingCalled","params":{"name":"onAppRouteDone","args":[{"webviewId":5,"path":"pages/user/userindex","query":{},"openType":"reLaunch","__ts__":1668763304574},1668763304577]}}
INFO  2022-11-18 17:21:44,581 app.py     _on_route_changed 588 Route changed, {'name': 'onAppRouteDone', 'args': [{'webviewId': 5, 'path': 'pages/user/userindex', 'query': {}, 'openType': 'reLaunch', '__ts__': 1668763304574}, 1668763304577]}
INFO  2022-11-18 17:21:44,588 minitest.py capture         575 capture setup.png
INFO  2022-11-18 17:21:44,589 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:21:44,589 connection.py send            201 SEND > {"id":"ef29639e-44cb-472a-8ed8-2b98f8061176","method":"App.captureScreenshot","params":{}}
ERROR 2022-11-18 17:21:45,726 connection.py _on_error       300 [WinError 10054] 远程主机强迫关闭了一个现有的连接。
INFO  2022-11-18 17:21:45,727 connection.py _ws_run_forever 169 websocket run forever shutdown
INFO  2022-11-18 17:22:44,765 minitest.py capture         575 capture setup.png
INFO  2022-11-18 17:22:44,765 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:22:44,765 connection.py send            201 SEND > {"id":"8f29b351-c467-4d55-bb72-bc0581ee29e4","method":"App.captureScreenshot","params":{}}
DEBUG 2022-11-18 17:22:44,765 minitest.py _miniTearDown   513 =========Current case Down: test_02_page_base_element=========
INFO  2022-11-18 17:22:44,766 minitest.py capture         575 capture teardown.png
INFO  2022-11-18 17:22:44,767 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:22:44,767 connection.py send            201 SEND > {"id":"2d770457-9d99-4643-9016-288159e33906","method":"App.captureScreenshot","params":{}}
INFO  2022-11-18 17:22:44,767 minitest.py capture         575 capture teardown.png
INFO  2022-11-18 17:22:44,767 basenative.py wrapper         23  call IdeNative.screen_shot
DEBUG 2022-11-18 17:22:44,767 connection.py send            201 SEND > {"id":"767aae3c-e25b-4b34-b13c-01877e814f53","method":"App.captureScreenshot","params":{}}
ERROR 2022-11-18 17:22:44,768 minitest.py _miniTearDown   532 Connection is already closed.
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 521, in _miniTearDown
    retry(2)(self.capture)("teardown")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\utils\utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 576, in capture
    self.native.screen_shot(path)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\basenative.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\app.py", line 179, in screen_shot
    self.connection.send("App.captureScreenshot")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 202, in send
    self._send(message)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 172, in _send
    return self._client.send(message)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\websocket\_app.py", line 235, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
ERROR 2022-11-18 17:22:44,776 assertbase.py _teardown_collect 273 <bound method HomePageTest.test_02_page_base_element of <case.homepage_test.HomePageTest testMethod=test_02_page_base_element>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\libs\unittest\case.py", line 32, in testPartExecutor
    yield
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\libs\unittest\case.py", line 109, in run
    self._miniSetUp()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 349, in _miniSetUp
    retry(2)(self.capture)("setup")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\utils\utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\framework\minitest.py", line 576, in capture
    self.native.screen_shot(path)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\basenative.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\native\wx_native\idenative.py", line 28, in screen_shot
    self.mini.app.screen_shot(filename, return_format)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\minium_log.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\app.py", line 179, in screen_shot
    self.connection.send("App.captureScreenshot")
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 202, in send
    self._send(message)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 172, in _send
    return self._client.send(message)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\websocket\_app.py", line 235, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
